// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBPHx0tqV2AU5rckGnoLMlNOPYtLn7AkDs',
    appId: '1:98755179351:web:87c7a9fd0b66f08e5d4412',
    messagingSenderId: '98755179351',
    projectId: 'newsapplication-2f26f',
    authDomain: 'newsapplication-2f26f.firebaseapp.com',
    storageBucket: 'newsapplication-2f26f.appspot.com',
    measurementId: 'G-90V8CF2G5Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALhWQvUtAFPmszteUkuP2uD7OCAQy3cCg',
    appId: '1:98755179351:android:68f9551d113afdf75d4412',
    messagingSenderId: '98755179351',
    projectId: 'newsapplication-2f26f',
    storageBucket: 'newsapplication-2f26f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCMvMHdCEzH6a7DKCC-UDIcFXyBryK6njg',
    appId: '1:98755179351:ios:f7a195e79c114f525d4412',
    messagingSenderId: '98755179351',
    projectId: 'newsapplication-2f26f',
    storageBucket: 'newsapplication-2f26f.appspot.com',
    iosBundleId: 'com.example.newsapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCMvMHdCEzH6a7DKCC-UDIcFXyBryK6njg',
    appId: '1:98755179351:ios:d53fc8cd3ed1d30a5d4412',
    messagingSenderId: '98755179351',
    projectId: 'newsapplication-2f26f',
    storageBucket: 'newsapplication-2f26f.appspot.com',
    iosBundleId: 'com.example.newsapp.RunnerTests',
  );
}
